# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sup/sup.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'sup/sup.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsup/sup.proto\x12\x03sup\" \n\nSupRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"\'\n\x0bSupResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2;\n\nSupService\x12-\n\x06SaySup\x12\x0f.sup.SupRequest\x1a\x10.sup.SupResponse\"\x00\x42,Z*github.com/maybecake/stacks/gen/go/sup;supb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sup.sup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/maybecake/stacks/gen/go/sup;sup'
  _globals['_SUPREQUEST']._serialized_start=22
  _globals['_SUPREQUEST']._serialized_end=54
  _globals['_SUPRESPONSE']._serialized_start=56
  _globals['_SUPRESPONSE']._serialized_end=95
  _globals['_SUPSERVICE']._serialized_start=97
  _globals['_SUPSERVICE']._serialized_end=156
# @@protoc_insertion_point(module_scope)
