// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file yo/yo.proto (package yo, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file yo/yo.proto.
 */
export const file_yo_yo = /*@__PURE__*/
  fileDesc("Cgt5by95by5wcm90bxICeW8iGQoJWW9SZXF1ZXN0EgwKBG5hbWUYASABKAkiHQoKWW9SZXNwb25zZRIPCgdtZXNzYWdlGAEgASgJMjUKCVlvU2VydmljZRIoCgVTYXlZbxINLnlvLllvUmVxdWVzdBoOLnlvLllvUmVzcG9uc2UiAEIqWihnaXRodWIuY29tL21heWJlY2FrZS9zdGFja3MvZ2VuL2dvL3lvO3lvYgZwcm90bzM");

/**
 * Describes the message yo.YoRequest.
 * Use `create(YoRequestSchema)` to create a new message.
 */
export const YoRequestSchema = /*@__PURE__*/
  messageDesc(file_yo_yo, 0);

/**
 * Describes the message yo.YoResponse.
 * Use `create(YoResponseSchema)` to create a new message.
 */
export const YoResponseSchema = /*@__PURE__*/
  messageDesc(file_yo_yo, 1);

/**
 * @generated from service yo.YoService
 */
export const YoService = /*@__PURE__*/
  serviceDesc(file_yo_yo, 0);

