// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file yo/yo.proto (package yo, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file yo/yo.proto.
 */
export declare const file_yo_yo: GenFile;

/**
 * @generated from message yo.YoRequest
 */
export declare type YoRequest = Message<"yo.YoRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message yo.YoRequest.
 * Use `create(YoRequestSchema)` to create a new message.
 */
export declare const YoRequestSchema: GenMessage<YoRequest>;

/**
 * @generated from message yo.YoResponse
 */
export declare type YoResponse = Message<"yo.YoResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message yo.YoResponse.
 * Use `create(YoResponseSchema)` to create a new message.
 */
export declare const YoResponseSchema: GenMessage<YoResponse>;

/**
 * @generated from service yo.YoService
 */
export declare const YoService: GenService<{
  /**
   * @generated from rpc yo.YoService.SayYo
   */
  sayYo: {
    methodKind: "unary";
    input: typeof YoRequestSchema;
    output: typeof YoResponseSchema;
  },
}>;

