# Docker container used for development
# Extra features are added via ./devcontainer/devcontainer.json definitions.

FROM ubuntu:24.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

# Install base dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    wget \
    git \
    unzip \
    vim \
    nodejs \
    python3 \
    golang \
    protobuf-compiler \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create and set up non-root user
RUN useradd -m -s /bin/bash devcontainer \
    && mkdir -p /home/devcontainer/.local/bin \
    && chown -R devcontainer:devcontainer /home/devcontainer

RUN go install github.com/bazelbuild/buildtools/buildifier@latest

# Add Buildifier to the PATH (optional, but recommended)
ENV PATH="$PATH:/usr/local/bin"

# # Install Gazelle
RUN go install github.com/bazelbuild/bazel-gazelle/cmd/gazelle@latest
ENV PATH="$PATH:$HOME/go/bin/"

RUN go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest

USER devcontainer
WORKDIR /home/devcontainer

# Default command
CMD ["/bin/bash"]

