// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file hello.proto (package hello, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file hello.proto.
 */
export declare const file_hello: GenFile;

/**
 * @generated from message hello.HelloRequest
 */
export declare type HelloRequest = Message<"hello.HelloRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message hello.HelloRequest.
 * Use `create(HelloRequestSchema)` to create a new message.
 */
export declare const HelloRequestSchema: GenMessage<HelloRequest>;

/**
 * @generated from message hello.HelloResponse
 */
export declare type HelloResponse = Message<"hello.HelloResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message hello.HelloResponse.
 * Use `create(HelloResponseSchema)` to create a new message.
 */
export declare const HelloResponseSchema: GenMessage<HelloResponse>;

/**
 * @generated from service hello.HelloService
 */
export declare const HelloService: GenService<{
  /**
   * @generated from rpc hello.HelloService.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof HelloRequestSchema;
    output: typeof HelloResponseSchema;
  },
}>;

