// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file hello.proto (package hello, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file hello.proto.
 */
export declare const file_hello: GenFile;

/**
 * @generated from message hello.HelloRequest
 */
export declare type HelloRequest = Message<"hello.HelloRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message hello.HelloRequest.
 * Use `create(HelloRequestSchema)` to create a new message.
 */
export declare const HelloRequestSchema: GenMessage<HelloRequest>;

/**
 * @generated from message hello.HelloResponse
 */
export declare type HelloResponse = Message<"hello.HelloResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message hello.HelloResponse.
 * Use `create(HelloResponseSchema)` to create a new message.
 */
export declare const HelloResponseSchema: GenMessage<HelloResponse>;

/**
 * @generated from message hello.GreetingTypeStat
 */
export declare type GreetingTypeStat = Message<"hello.GreetingTypeStat"> & {
  /**
   * @generated from field: string greeting_type = 1;
   */
  greetingType: string;

  /**
   * @generated from field: int64 count = 2;
   */
  count: bigint;
};

/**
 * Describes the message hello.GreetingTypeStat.
 * Use `create(GreetingTypeStatSchema)` to create a new message.
 */
export declare const GreetingTypeStatSchema: GenMessage<GreetingTypeStat>;

/**
 * @generated from message hello.NameFrequency
 */
export declare type NameFrequency = Message<"hello.NameFrequency"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: int64 count = 2;
   */
  count: bigint;
};

/**
 * Describes the message hello.NameFrequency.
 * Use `create(NameFrequencySchema)` to create a new message.
 */
export declare const NameFrequencySchema: GenMessage<NameFrequency>;

/**
 * @generated from message hello.ListGreetingTypeStatsRequest
 */
export declare type ListGreetingTypeStatsRequest = Message<"hello.ListGreetingTypeStatsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message hello.ListGreetingTypeStatsRequest.
 * Use `create(ListGreetingTypeStatsRequestSchema)` to create a new message.
 */
export declare const ListGreetingTypeStatsRequestSchema: GenMessage<ListGreetingTypeStatsRequest>;

/**
 * @generated from message hello.ListGreetingTypeStatsResponse
 */
export declare type ListGreetingTypeStatsResponse = Message<"hello.ListGreetingTypeStatsResponse"> & {
  /**
   * @generated from field: repeated hello.GreetingTypeStat greeting_types = 1;
   */
  greetingTypes: GreetingTypeStat[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message hello.ListGreetingTypeStatsResponse.
 * Use `create(ListGreetingTypeStatsResponseSchema)` to create a new message.
 */
export declare const ListGreetingTypeStatsResponseSchema: GenMessage<ListGreetingTypeStatsResponse>;

/**
 * @generated from message hello.ListGreetedNamesRequest
 */
export declare type ListGreetedNamesRequest = Message<"hello.ListGreetedNamesRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message hello.ListGreetedNamesRequest.
 * Use `create(ListGreetedNamesRequestSchema)` to create a new message.
 */
export declare const ListGreetedNamesRequestSchema: GenMessage<ListGreetedNamesRequest>;

/**
 * @generated from message hello.ListGreetedNamesResponse
 */
export declare type ListGreetedNamesResponse = Message<"hello.ListGreetedNamesResponse"> & {
  /**
   * @generated from field: repeated hello.NameFrequency names = 1;
   */
  names: NameFrequency[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message hello.ListGreetedNamesResponse.
 * Use `create(ListGreetedNamesResponseSchema)` to create a new message.
 */
export declare const ListGreetedNamesResponseSchema: GenMessage<ListGreetedNamesResponse>;

/**
 * @generated from service hello.HelloService
 */
export declare const HelloService: GenService<{
  /**
   * @generated from rpc hello.HelloService.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof HelloRequestSchema;
    output: typeof HelloResponseSchema;
  },
  /**
   * @generated from rpc hello.HelloService.ListGreetingTypeStats
   */
  listGreetingTypeStats: {
    methodKind: "unary";
    input: typeof ListGreetingTypeStatsRequestSchema;
    output: typeof ListGreetingTypeStatsResponseSchema;
  },
  /**
   * @generated from rpc hello.HelloService.ListGreetedNames
   */
  listGreetedNames: {
    methodKind: "unary";
    input: typeof ListGreetedNamesRequestSchema;
    output: typeof ListGreetedNamesResponseSchema;
  },
}>;

