// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file sup/sup.proto (package sup, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sup/sup.proto.
 */
export declare const file_sup_sup: GenFile;

/**
 * @generated from message sup.SupRequest
 */
export declare type SupRequest = Message<"sup.SupRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message sup.SupRequest.
 * Use `create(SupRequestSchema)` to create a new message.
 */
export declare const SupRequestSchema: GenMessage<SupRequest>;

/**
 * @generated from message sup.SupResponse
 */
export declare type SupResponse = Message<"sup.SupResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message sup.SupResponse.
 * Use `create(SupResponseSchema)` to create a new message.
 */
export declare const SupResponseSchema: GenMessage<SupResponse>;

/**
 * @generated from service sup.SupService
 */
export declare const SupService: GenService<{
  /**
   * @generated from rpc sup.SupService.SaySup
   */
  saySup: {
    methodKind: "unary";
    input: typeof SupRequestSchema;
    output: typeof SupResponseSchema;
  },
}>;

