// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: greeting.sql

package pgdb

import (
	"context"
)

const getAllStats = `-- name: GetAllStats :many
SELECT greeting_type, count
FROM greeting_stats
ORDER BY greeting_type
`

func (q *Queries) GetAllStats(ctx context.Context) ([]GreetingStat, error) {
	rows, err := q.db.QueryContext(ctx, getAllStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GreetingStat
	for rows.Next() {
		var i GreetingStat
		if err := rows.Scan(&i.GreetingType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNameFrequencies = `-- name: GetNameFrequencies :many
SELECT name, COUNT(*) AS count
FROM greeting_log
GROUP BY name
ORDER BY count DESC
`

type GetNameFrequenciesRow struct {
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

func (q *Queries) GetNameFrequencies(ctx context.Context) ([]GetNameFrequenciesRow, error) {
	rows, err := q.db.QueryContext(ctx, getNameFrequencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNameFrequenciesRow
	for rows.Next() {
		var i GetNameFrequenciesRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGreetingLog = `-- name: InsertGreetingLog :exec
INSERT INTO greeting_log (greeting_type, name)
VALUES ($1, $2)
`

type InsertGreetingLogParams struct {
	GreetingType string `json:"greeting_type"`
	Name         string `json:"name"`
}

func (q *Queries) InsertGreetingLog(ctx context.Context, arg InsertGreetingLogParams) error {
	_, err := q.db.ExecContext(ctx, insertGreetingLog, arg.GreetingType, arg.Name)
	return err
}

const upsertGreetingStats = `-- name: UpsertGreetingStats :exec
INSERT INTO greeting_stats (greeting_type, count)
VALUES ($1, 1)
ON CONFLICT (greeting_type)
DO UPDATE SET count = greeting_stats.count + 1
`

func (q *Queries) UpsertGreetingStats(ctx context.Context, greetingType string) error {
	_, err := q.db.ExecContext(ctx, upsertGreetingStats, greetingType)
	return err
}
