// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invite.sql

package pgdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const confirmedAttendeeCount = `-- name: ConfirmedAttendeeCount :one
SELECT COALESCE(SUM(ac.cnt), 0)::int AS total
FROM (
    SELECT COUNT(*) AS cnt
    FROM invite__rsvp_attendees ra
    JOIN invite__rsvps r ON r.id = ra.rsvp_id
    WHERE r.event_id = $1 AND r.status = 'confirmed'
    GROUP BY r.id
) ac
`

func (q *Queries) ConfirmedAttendeeCount(ctx context.Context, eventID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, confirmedAttendeeCount, eventID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const deleteInvitee = `-- name: DeleteInvitee :exec
DELETE FROM invite__invitees WHERE id = $1
`

func (q *Queries) DeleteInvitee(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInvitee, id)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, public_token, host_user_id, name, venue, description, datetime, capacity, allow_siblings, require_parent_stay, created_at FROM invite__events WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (InviteEvent, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i InviteEvent
	err := row.Scan(
		&i.ID,
		&i.PublicToken,
		&i.HostUserID,
		&i.Name,
		&i.Venue,
		&i.Description,
		&i.Datetime,
		&i.Capacity,
		&i.AllowSiblings,
		&i.RequireParentStay,
		&i.CreatedAt,
	)
	return i, err
}

const getEventByPublicToken = `-- name: GetEventByPublicToken :one
SELECT id, public_token, host_user_id, name, venue, description, datetime, capacity, allow_siblings, require_parent_stay, created_at FROM invite__events WHERE public_token = $1 LIMIT 1
`

func (q *Queries) GetEventByPublicToken(ctx context.Context, publicToken uuid.UUID) (InviteEvent, error) {
	row := q.db.QueryRowContext(ctx, getEventByPublicToken, publicToken)
	var i InviteEvent
	err := row.Scan(
		&i.ID,
		&i.PublicToken,
		&i.HostUserID,
		&i.Name,
		&i.Venue,
		&i.Description,
		&i.Datetime,
		&i.Capacity,
		&i.AllowSiblings,
		&i.RequireParentStay,
		&i.CreatedAt,
	)
	return i, err
}

const getHouseholdByID = `-- name: GetHouseholdByID :one
SELECT id, name, created_at FROM households WHERE id = $1 LIMIT 1
`

func (q *Queries) GetHouseholdByID(ctx context.Context, id uuid.UUID) (Household, error) {
	row := q.db.QueryRowContext(ctx, getHouseholdByID, id)
	var i Household
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getHouseholdChildMembers = `-- name: GetHouseholdChildMembers :many
SELECT household_id, person_id, role FROM household_members WHERE household_id = $1 AND role = 'child'
`

func (q *Queries) GetHouseholdChildMembers(ctx context.Context, householdID uuid.UUID) ([]HouseholdMember, error) {
	rows, err := q.db.QueryContext(ctx, getHouseholdChildMembers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HouseholdMember
	for rows.Next() {
		var i HouseholdMember
		if err := rows.Scan(&i.HouseholdID, &i.PersonID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHouseholdClaimByToken = `-- name: GetHouseholdClaimByToken :one
SELECT id, household_id, event_id, claim_token, claimed_at, created_at FROM household_claims WHERE claim_token = $1 LIMIT 1
`

func (q *Queries) GetHouseholdClaimByToken(ctx context.Context, claimToken uuid.UUID) (HouseholdClaim, error) {
	row := q.db.QueryRowContext(ctx, getHouseholdClaimByToken, claimToken)
	var i HouseholdClaim
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.EventID,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getHouseholdOwner = `-- name: GetHouseholdOwner :one
SELECT user_id FROM user_households WHERE household_id = $1 LIMIT 1
`

func (q *Queries) GetHouseholdOwner(ctx context.Context, householdID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getHouseholdOwner, householdID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getInviteeByID = `-- name: GetInviteeByID :one
SELECT id, event_id, person_id, household_id, created_at FROM invite__invitees WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInviteeByID(ctx context.Context, id uuid.UUID) (InviteInvitee, error) {
	row := q.db.QueryRowContext(ctx, getInviteeByID, id)
	var i InviteInvitee
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PersonID,
		&i.HouseholdID,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonByID = `-- name: GetPersonByID :one
SELECT id, name, type, phone, email, created_at FROM persons WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPersonByID(ctx context.Context, id uuid.UUID) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPersonByID, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one

INSERT INTO invite__events (host_user_id, name, venue, description, datetime, capacity, allow_siblings, require_parent_stay)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, public_token, host_user_id, name, venue, description, datetime, capacity, allow_siblings, require_parent_stay, created_at
`

type InsertEventParams struct {
	HostUserID        string         `json:"host_user_id"`
	Name              string         `json:"name"`
	Venue             string         `json:"venue"`
	Description       sql.NullString `json:"description"`
	Datetime          time.Time      `json:"datetime"`
	Capacity          int32          `json:"capacity"`
	AllowSiblings     bool           `json:"allow_siblings"`
	RequireParentStay bool           `json:"require_parent_stay"`
}

// ── Events ────────────────────────────────────────────────────────────────────
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (InviteEvent, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.HostUserID,
		arg.Name,
		arg.Venue,
		arg.Description,
		arg.Datetime,
		arg.Capacity,
		arg.AllowSiblings,
		arg.RequireParentStay,
	)
	var i InviteEvent
	err := row.Scan(
		&i.ID,
		&i.PublicToken,
		&i.HostUserID,
		&i.Name,
		&i.Venue,
		&i.Description,
		&i.Datetime,
		&i.Capacity,
		&i.AllowSiblings,
		&i.RequireParentStay,
		&i.CreatedAt,
	)
	return i, err
}

const insertHousehold = `-- name: InsertHousehold :one

INSERT INTO households (name)
VALUES ($1)
RETURNING id, name, created_at
`

// ── Households ────────────────────────────────────────────────────────────────
func (q *Queries) InsertHousehold(ctx context.Context, name sql.NullString) (Household, error) {
	row := q.db.QueryRowContext(ctx, insertHousehold, name)
	var i Household
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const insertHouseholdClaim = `-- name: InsertHouseholdClaim :one

INSERT INTO household_claims (household_id, event_id, claim_token)
VALUES ($1, $2, gen_random_uuid())
RETURNING id, household_id, event_id, claim_token, claimed_at, created_at
`

type InsertHouseholdClaimParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	EventID     uuid.UUID `json:"event_id"`
}

// ── Claims ────────────────────────────────────────────────────────────────────
func (q *Queries) InsertHouseholdClaim(ctx context.Context, arg InsertHouseholdClaimParams) (HouseholdClaim, error) {
	row := q.db.QueryRowContext(ctx, insertHouseholdClaim, arg.HouseholdID, arg.EventID)
	var i HouseholdClaim
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.EventID,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertHouseholdMember = `-- name: InsertHouseholdMember :one
INSERT INTO household_members (household_id, person_id, role)
VALUES ($1, $2, $3)
RETURNING household_id, person_id, role
`

type InsertHouseholdMemberParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	PersonID    uuid.UUID `json:"person_id"`
	Role        string    `json:"role"`
}

func (q *Queries) InsertHouseholdMember(ctx context.Context, arg InsertHouseholdMemberParams) (HouseholdMember, error) {
	row := q.db.QueryRowContext(ctx, insertHouseholdMember, arg.HouseholdID, arg.PersonID, arg.Role)
	var i HouseholdMember
	err := row.Scan(&i.HouseholdID, &i.PersonID, &i.Role)
	return i, err
}

const insertInvitee = `-- name: InsertInvitee :one

INSERT INTO invite__invitees (event_id, person_id, household_id)
VALUES ($1, $2, $3)
RETURNING id, event_id, person_id, household_id, created_at
`

type InsertInviteeParams struct {
	EventID     uuid.UUID `json:"event_id"`
	PersonID    uuid.UUID `json:"person_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

// ── Invitees ──────────────────────────────────────────────────────────────────
func (q *Queries) InsertInvitee(ctx context.Context, arg InsertInviteeParams) (InviteInvitee, error) {
	row := q.db.QueryRowContext(ctx, insertInvitee, arg.EventID, arg.PersonID, arg.HouseholdID)
	var i InviteInvitee
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.PersonID,
		&i.HouseholdID,
		&i.CreatedAt,
	)
	return i, err
}

const insertPerson = `-- name: InsertPerson :one

INSERT INTO persons (name, type, phone, email)
VALUES ($1, $2, $3, $4)
RETURNING id, name, type, phone, email, created_at
`

type InsertPersonParams struct {
	Name  string         `json:"name"`
	Type  string         `json:"type"`
	Phone sql.NullString `json:"phone"`
	Email sql.NullString `json:"email"`
}

// ── Persons ───────────────────────────────────────────────────────────────────
func (q *Queries) InsertPerson(ctx context.Context, arg InsertPersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, insertPerson,
		arg.Name,
		arg.Type,
		arg.Phone,
		arg.Email,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const insertRSVP = `-- name: InsertRSVP :one

INSERT INTO invite__rsvps (event_id, household_id, status, emergency_contact_name, emergency_contact_phone)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, event_id, household_id, status, emergency_contact_name, emergency_contact_phone, created_at
`

type InsertRSVPParams struct {
	EventID               uuid.UUID `json:"event_id"`
	HouseholdID           uuid.UUID `json:"household_id"`
	Status                string    `json:"status"`
	EmergencyContactName  string    `json:"emergency_contact_name"`
	EmergencyContactPhone string    `json:"emergency_contact_phone"`
}

// ── RSVPs ─────────────────────────────────────────────────────────────────────
func (q *Queries) InsertRSVP(ctx context.Context, arg InsertRSVPParams) (InviteRsvp, error) {
	row := q.db.QueryRowContext(ctx, insertRSVP,
		arg.EventID,
		arg.HouseholdID,
		arg.Status,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
	)
	var i InviteRsvp
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.HouseholdID,
		&i.Status,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.CreatedAt,
	)
	return i, err
}

const insertRSVPAttendee = `-- name: InsertRSVPAttendee :exec
INSERT INTO invite__rsvp_attendees (rsvp_id, person_id)
VALUES ($1, $2)
`

type InsertRSVPAttendeeParams struct {
	RsvpID   uuid.UUID `json:"rsvp_id"`
	PersonID uuid.UUID `json:"person_id"`
}

func (q *Queries) InsertRSVPAttendee(ctx context.Context, arg InsertRSVPAttendeeParams) error {
	_, err := q.db.ExecContext(ctx, insertRSVPAttendee, arg.RsvpID, arg.PersonID)
	return err
}

const insertUserHousehold = `-- name: InsertUserHousehold :exec
INSERT INTO user_households (user_id, household_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertUserHouseholdParams struct {
	UserID      string    `json:"user_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) InsertUserHousehold(ctx context.Context, arg InsertUserHouseholdParams) error {
	_, err := q.db.ExecContext(ctx, insertUserHousehold, arg.UserID, arg.HouseholdID)
	return err
}

const inviteeHouseholdHasConfirmedRSVP = `-- name: InviteeHouseholdHasConfirmedRSVP :one
SELECT COUNT(*) > 0 AS has_rsvp
FROM invite__rsvps r
JOIN invite__invitees ii ON ii.event_id = r.event_id AND ii.household_id = r.household_id
WHERE ii.id = $1 AND r.status = 'confirmed'
`

func (q *Queries) InviteeHouseholdHasConfirmedRSVP(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, inviteeHouseholdHasConfirmedRSVP, id)
	var has_rsvp bool
	err := row.Scan(&has_rsvp)
	return has_rsvp, err
}

const listEventsForHost = `-- name: ListEventsForHost :many
SELECT id, public_token, host_user_id, name, venue, description, datetime, capacity, allow_siblings, require_parent_stay, created_at FROM invite__events
WHERE host_user_id = $1
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListEventsForHostParams struct {
	HostUserID string `json:"host_user_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListEventsForHost(ctx context.Context, arg ListEventsForHostParams) ([]InviteEvent, error) {
	rows, err := q.db.QueryContext(ctx, listEventsForHost, arg.HostUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InviteEvent
	for rows.Next() {
		var i InviteEvent
		if err := rows.Scan(
			&i.ID,
			&i.PublicToken,
			&i.HostUserID,
			&i.Name,
			&i.Venue,
			&i.Description,
			&i.Datetime,
			&i.Capacity,
			&i.AllowSiblings,
			&i.RequireParentStay,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdGroups = `-- name: ListHouseholdGroups :many
SELECT
    h.id                        AS household_id,
    h.name                      AS household_name,
    r.id                        AS rsvp_id,
    r.status                    AS rsvp_status,
    r.emergency_contact_name,
    r.emergency_contact_phone,
    r.created_at                AS rsvp_created_at,
    p.id                        AS person_id,
    p.name                      AS person_name,
    p.type                      AS person_type,
    p.phone                     AS person_phone,
    p.email                     AS person_email
FROM invite__rsvps r
JOIN households h ON h.id = r.household_id
JOIN invite__rsvp_attendees ra ON ra.rsvp_id = r.id
JOIN persons p ON p.id = ra.person_id
WHERE r.event_id = $1 AND r.status = 'confirmed'
ORDER BY h.name, p.name
LIMIT $2 OFFSET $3
`

type ListHouseholdGroupsParams struct {
	EventID uuid.UUID `json:"event_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type ListHouseholdGroupsRow struct {
	HouseholdID           uuid.UUID      `json:"household_id"`
	HouseholdName         sql.NullString `json:"household_name"`
	RsvpID                uuid.UUID      `json:"rsvp_id"`
	RsvpStatus            string         `json:"rsvp_status"`
	EmergencyContactName  string         `json:"emergency_contact_name"`
	EmergencyContactPhone string         `json:"emergency_contact_phone"`
	RsvpCreatedAt         time.Time      `json:"rsvp_created_at"`
	PersonID              uuid.UUID      `json:"person_id"`
	PersonName            string         `json:"person_name"`
	PersonType            string         `json:"person_type"`
	PersonPhone           sql.NullString `json:"person_phone"`
	PersonEmail           sql.NullString `json:"person_email"`
}

func (q *Queries) ListHouseholdGroups(ctx context.Context, arg ListHouseholdGroupsParams) ([]ListHouseholdGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listHouseholdGroups, arg.EventID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHouseholdGroupsRow
	for rows.Next() {
		var i ListHouseholdGroupsRow
		if err := rows.Scan(
			&i.HouseholdID,
			&i.HouseholdName,
			&i.RsvpID,
			&i.RsvpStatus,
			&i.EmergencyContactName,
			&i.EmergencyContactPhone,
			&i.RsvpCreatedAt,
			&i.PersonID,
			&i.PersonName,
			&i.PersonType,
			&i.PersonPhone,
			&i.PersonEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInviteesWithStatus = `-- name: ListInviteesWithStatus :many
SELECT
    ii.id           AS invitee_id,
    ii.event_id,
    ii.person_id,
    ii.household_id,
    p.name          AS person_name,
    p.type          AS person_type,
    p.phone         AS person_phone,
    p.email         AS person_email,
    COALESCE(r.status, '')  AS rsvp_status
FROM invite__invitees ii
JOIN persons p ON p.id = ii.person_id
LEFT JOIN invite__rsvps r ON r.event_id = ii.event_id AND r.household_id = ii.household_id
WHERE ii.event_id = $1
ORDER BY p.name
LIMIT $2 OFFSET $3
`

type ListInviteesWithStatusParams struct {
	EventID uuid.UUID `json:"event_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type ListInviteesWithStatusRow struct {
	InviteeID   uuid.UUID      `json:"invitee_id"`
	EventID     uuid.UUID      `json:"event_id"`
	PersonID    uuid.UUID      `json:"person_id"`
	HouseholdID uuid.UUID      `json:"household_id"`
	PersonName  string         `json:"person_name"`
	PersonType  string         `json:"person_type"`
	PersonPhone sql.NullString `json:"person_phone"`
	PersonEmail sql.NullString `json:"person_email"`
	RsvpStatus  string         `json:"rsvp_status"`
}

func (q *Queries) ListInviteesWithStatus(ctx context.Context, arg ListInviteesWithStatusParams) ([]ListInviteesWithStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listInviteesWithStatus, arg.EventID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInviteesWithStatusRow
	for rows.Next() {
		var i ListInviteesWithStatusRow
		if err := rows.Scan(
			&i.InviteeID,
			&i.EventID,
			&i.PersonID,
			&i.HouseholdID,
			&i.PersonName,
			&i.PersonType,
			&i.PersonPhone,
			&i.PersonEmail,
			&i.RsvpStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonsForEvent = `-- name: ListPersonsForEvent :many
SELECT DISTINCT p.id, p.name, p.type, p.phone, p.email, p.created_at
FROM persons p
JOIN invite__invitees ii ON ii.person_id = p.id
JOIN invite__events e ON e.id = ii.event_id
WHERE e.public_token = $1
ORDER BY p.name
LIMIT $2 OFFSET $3
`

type ListPersonsForEventParams struct {
	PublicToken uuid.UUID `json:"public_token"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListPersonsForEvent(ctx context.Context, arg ListPersonsForEventParams) ([]Person, error) {
	rows, err := q.db.QueryContext(ctx, listPersonsForEvent, arg.PublicToken, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Phone,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonsForHost = `-- name: ListPersonsForHost :many
SELECT DISTINCT p.id, p.name, p.type, p.phone, p.email, p.created_at
FROM persons p
JOIN invite__invitees ii ON ii.person_id = p.id
JOIN invite__events e ON e.id = ii.event_id
WHERE e.host_user_id = $1
ORDER BY p.name
LIMIT $2 OFFSET $3
`

type ListPersonsForHostParams struct {
	HostUserID string `json:"host_user_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListPersonsForHost(ctx context.Context, arg ListPersonsForHostParams) ([]Person, error) {
	rows, err := q.db.QueryContext(ctx, listPersonsForHost, arg.HostUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Phone,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonsForOwner = `-- name: ListPersonsForOwner :many
SELECT DISTINCT p.id, p.name, p.type, p.phone, p.email, p.created_at
FROM persons p
JOIN household_members hm ON hm.person_id = p.id
JOIN user_households uh ON uh.household_id = hm.household_id
WHERE uh.user_id = $1
ORDER BY p.name
LIMIT $2 OFFSET $3
`

type ListPersonsForOwnerParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListPersonsForOwner(ctx context.Context, arg ListPersonsForOwnerParams) ([]Person, error) {
	rows, err := q.db.QueryContext(ctx, listPersonsForOwner, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Phone,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markClaimClaimed = `-- name: MarkClaimClaimed :exec
UPDATE household_claims SET claimed_at = now() WHERE claim_token = $1
`

func (q *Queries) MarkClaimClaimed(ctx context.Context, claimToken uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markClaimClaimed, claimToken)
	return err
}

const personIsAccessibleToHost = `-- name: PersonIsAccessibleToHost :one
SELECT COUNT(*) > 0 AS accessible
FROM invite__invitees ii
JOIN invite__events e ON e.id = ii.event_id
WHERE ii.person_id = $1 AND e.host_user_id = $2
`

type PersonIsAccessibleToHostParams struct {
	PersonID   uuid.UUID `json:"person_id"`
	HostUserID string    `json:"host_user_id"`
}

func (q *Queries) PersonIsAccessibleToHost(ctx context.Context, arg PersonIsAccessibleToHostParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, personIsAccessibleToHost, arg.PersonID, arg.HostUserID)
	var accessible bool
	err := row.Scan(&accessible)
	return accessible, err
}

const personIsAccessibleToOwner = `-- name: PersonIsAccessibleToOwner :one
SELECT COUNT(*) > 0 AS accessible
FROM household_members hm
JOIN user_households uh ON uh.household_id = hm.household_id
WHERE hm.person_id = $1 AND uh.user_id = $2
`

type PersonIsAccessibleToOwnerParams struct {
	PersonID uuid.UUID `json:"person_id"`
	UserID   string    `json:"user_id"`
}

func (q *Queries) PersonIsAccessibleToOwner(ctx context.Context, arg PersonIsAccessibleToOwnerParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, personIsAccessibleToOwner, arg.PersonID, arg.UserID)
	var accessible bool
	err := row.Scan(&accessible)
	return accessible, err
}

const personIsAccessibleViaEvent = `-- name: PersonIsAccessibleViaEvent :one
SELECT COUNT(*) > 0 AS accessible
FROM invite__invitees ii
JOIN invite__events e ON e.id = ii.event_id
WHERE ii.person_id = $1 AND e.public_token = $2
`

type PersonIsAccessibleViaEventParams struct {
	PersonID    uuid.UUID `json:"person_id"`
	PublicToken uuid.UUID `json:"public_token"`
}

func (q *Queries) PersonIsAccessibleViaEvent(ctx context.Context, arg PersonIsAccessibleViaEventParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, personIsAccessibleViaEvent, arg.PersonID, arg.PublicToken)
	var accessible bool
	err := row.Scan(&accessible)
	return accessible, err
}
