// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"time"
)

type GreetingLog struct {
	ID           int32     `json:"id"`
	GreetingType string    `json:"greeting_type"`
	Name         string    `json:"name"`
	GreetedAt    time.Time `json:"greeted_at"`
}

type GreetingStat struct {
	GreetingType string `json:"greeting_type"`
	Count        int32  `json:"count"`
}
