// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file invite/invite.proto (package invite, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file invite/invite.proto.
 */
export declare const file_invite_invite: GenFile;

/**
 * @generated from message invite.Person
 */
export declare type Person = Message<"invite.Person"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: invite.PersonType type = 3;
   */
  type: PersonType;

  /**
   * @generated from field: string phone = 4;
   */
  phone: string;

  /**
   * @generated from field: string email = 5;
   */
  email: string;
};

/**
 * Describes the message invite.Person.
 * Use `create(PersonSchema)` to create a new message.
 */
export declare const PersonSchema: GenMessage<Person>;

/**
 * @generated from message invite.Household
 */
export declare type Household = Message<"invite.Household"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message invite.Household.
 * Use `create(HouseholdSchema)` to create a new message.
 */
export declare const HouseholdSchema: GenMessage<Household>;

/**
 * @generated from message invite.HouseholdMember
 */
export declare type HouseholdMember = Message<"invite.HouseholdMember"> & {
  /**
   * @generated from field: string household_id = 1;
   */
  householdId: string;

  /**
   * @generated from field: string person_id = 2;
   */
  personId: string;

  /**
   * @generated from field: invite.MemberRole role = 3;
   */
  role: MemberRole;
};

/**
 * Describes the message invite.HouseholdMember.
 * Use `create(HouseholdMemberSchema)` to create a new message.
 */
export declare const HouseholdMemberSchema: GenMessage<HouseholdMember>;

/**
 * Event datetime is stored as Unix seconds (UTC).
 *
 * @generated from message invite.Event
 */
export declare type Event = Message<"invite.Event"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string public_token = 2;
   */
  publicToken: string;

  /**
   * @generated from field: string host_user_id = 3;
   */
  hostUserId: string;

  /**
   * @generated from field: string name = 4;
   */
  name: string;

  /**
   * @generated from field: string venue = 5;
   */
  venue: string;

  /**
   * @generated from field: string description = 6;
   */
  description: string;

  /**
   * @generated from field: int64 datetime_unix = 7;
   */
  datetimeUnix: bigint;

  /**
   * @generated from field: int32 capacity = 8;
   */
  capacity: number;

  /**
   * @generated from field: bool allow_siblings = 9;
   */
  allowSiblings: boolean;

  /**
   * @generated from field: bool require_parent_stay = 10;
   */
  requireParentStay: boolean;
};

/**
 * Describes the message invite.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export declare const EventSchema: GenMessage<Event>;

/**
 * @generated from message invite.Invitee
 */
export declare type Invitee = Message<"invite.Invitee"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string event_id = 2;
   */
  eventId: string;

  /**
   * @generated from field: string person_id = 3;
   */
  personId: string;

  /**
   * @generated from field: string household_id = 4;
   */
  householdId: string;
};

/**
 * Describes the message invite.Invitee.
 * Use `create(InviteeSchema)` to create a new message.
 */
export declare const InviteeSchema: GenMessage<Invitee>;

/**
 * @generated from message invite.InviteeWithStatus
 */
export declare type InviteeWithStatus = Message<"invite.InviteeWithStatus"> & {
  /**
   * @generated from field: invite.Invitee invitee = 1;
   */
  invitee?: Invitee;

  /**
   * @generated from field: invite.Person person = 2;
   */
  person?: Person;

  /**
   * @generated from field: invite.RSVPStatus rsvp_status = 3;
   */
  rsvpStatus: RSVPStatus;
};

/**
 * Describes the message invite.InviteeWithStatus.
 * Use `create(InviteeWithStatusSchema)` to create a new message.
 */
export declare const InviteeWithStatusSchema: GenMessage<InviteeWithStatus>;

/**
 * @generated from message invite.RSVP
 */
export declare type RSVP = Message<"invite.RSVP"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string event_id = 2;
   */
  eventId: string;

  /**
   * @generated from field: string household_id = 3;
   */
  householdId: string;

  /**
   * @generated from field: invite.RSVPStatus status = 4;
   */
  status: RSVPStatus;

  /**
   * @generated from field: string emergency_contact_name = 5;
   */
  emergencyContactName: string;

  /**
   * @generated from field: string emergency_contact_phone = 6;
   */
  emergencyContactPhone: string;
};

/**
 * Describes the message invite.RSVP.
 * Use `create(RSVPSchema)` to create a new message.
 */
export declare const RSVPSchema: GenMessage<RSVP>;

/**
 * @generated from message invite.RSVPAttendee
 */
export declare type RSVPAttendee = Message<"invite.RSVPAttendee"> & {
  /**
   * @generated from field: string rsvp_id = 1;
   */
  rsvpId: string;

  /**
   * @generated from field: string person_id = 2;
   */
  personId: string;
};

/**
 * Describes the message invite.RSVPAttendee.
 * Use `create(RSVPAttendeeSchema)` to create a new message.
 */
export declare const RSVPAttendeeSchema: GenMessage<RSVPAttendee>;

/**
 * HouseholdGroup is the host-dashboard view of one household's RSVP.
 *
 * @generated from message invite.HouseholdGroup
 */
export declare type HouseholdGroup = Message<"invite.HouseholdGroup"> & {
  /**
   * @generated from field: invite.Household household = 1;
   */
  household?: Household;

  /**
   * @generated from field: invite.RSVP rsvp = 2;
   */
  rsvp?: RSVP;

  /**
   * @generated from field: repeated invite.Person attendees = 3;
   */
  attendees: Person[];

  /**
   * @generated from field: string emergency_contact_name = 4;
   */
  emergencyContactName: string;

  /**
   * @generated from field: string emergency_contact_phone = 5;
   */
  emergencyContactPhone: string;
};

/**
 * Describes the message invite.HouseholdGroup.
 * Use `create(HouseholdGroupSchema)` to create a new message.
 */
export declare const HouseholdGroupSchema: GenMessage<HouseholdGroup>;

/**
 * @generated from message invite.CreateEventRequest
 */
export declare type CreateEventRequest = Message<"invite.CreateEventRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string venue = 2;
   */
  venue: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: int64 datetime_unix = 4;
   */
  datetimeUnix: bigint;

  /**
   * @generated from field: int32 capacity = 5;
   */
  capacity: number;

  /**
   * @generated from field: bool allow_siblings = 6;
   */
  allowSiblings: boolean;

  /**
   * @generated from field: bool require_parent_stay = 7;
   */
  requireParentStay: boolean;
};

/**
 * Describes the message invite.CreateEventRequest.
 * Use `create(CreateEventRequestSchema)` to create a new message.
 */
export declare const CreateEventRequestSchema: GenMessage<CreateEventRequest>;

/**
 * @generated from message invite.GetEventRequest
 */
export declare type GetEventRequest = Message<"invite.GetEventRequest"> & {
  /**
   * @generated from field: string public_token = 1;
   */
  publicToken: string;
};

/**
 * Describes the message invite.GetEventRequest.
 * Use `create(GetEventRequestSchema)` to create a new message.
 */
export declare const GetEventRequestSchema: GenMessage<GetEventRequest>;

/**
 * @generated from message invite.AddInviteeRequest
 */
export declare type AddInviteeRequest = Message<"invite.AddInviteeRequest"> & {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId: string;

  /**
   * @generated from field: string person_id = 2;
   */
  personId: string;
};

/**
 * Describes the message invite.AddInviteeRequest.
 * Use `create(AddInviteeRequestSchema)` to create a new message.
 */
export declare const AddInviteeRequestSchema: GenMessage<AddInviteeRequest>;

/**
 * @generated from message invite.AddHouseholdInviteesRequest
 */
export declare type AddHouseholdInviteesRequest = Message<"invite.AddHouseholdInviteesRequest"> & {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId: string;

  /**
   * @generated from field: string household_id = 2;
   */
  householdId: string;
};

/**
 * Describes the message invite.AddHouseholdInviteesRequest.
 * Use `create(AddHouseholdInviteesRequestSchema)` to create a new message.
 */
export declare const AddHouseholdInviteesRequestSchema: GenMessage<AddHouseholdInviteesRequest>;

/**
 * @generated from message invite.AddHouseholdInviteesResponse
 */
export declare type AddHouseholdInviteesResponse = Message<"invite.AddHouseholdInviteesResponse"> & {
  /**
   * @generated from field: repeated invite.Invitee invitees = 1;
   */
  invitees: Invitee[];
};

/**
 * Describes the message invite.AddHouseholdInviteesResponse.
 * Use `create(AddHouseholdInviteesResponseSchema)` to create a new message.
 */
export declare const AddHouseholdInviteesResponseSchema: GenMessage<AddHouseholdInviteesResponse>;

/**
 * @generated from message invite.RemoveInviteeRequest
 */
export declare type RemoveInviteeRequest = Message<"invite.RemoveInviteeRequest"> & {
  /**
   * @generated from field: string invitee_id = 1;
   */
  inviteeId: string;
};

/**
 * Describes the message invite.RemoveInviteeRequest.
 * Use `create(RemoveInviteeRequestSchema)` to create a new message.
 */
export declare const RemoveInviteeRequestSchema: GenMessage<RemoveInviteeRequest>;

/**
 * @generated from message invite.RemoveInviteeResponse
 */
export declare type RemoveInviteeResponse = Message<"invite.RemoveInviteeResponse"> & {
};

/**
 * Describes the message invite.RemoveInviteeResponse.
 * Use `create(RemoveInviteeResponseSchema)` to create a new message.
 */
export declare const RemoveInviteeResponseSchema: GenMessage<RemoveInviteeResponse>;

/**
 * @generated from message invite.ListInviteesRequest
 */
export declare type ListInviteesRequest = Message<"invite.ListInviteesRequest"> & {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId: string;
};

/**
 * Describes the message invite.ListInviteesRequest.
 * Use `create(ListInviteesRequestSchema)` to create a new message.
 */
export declare const ListInviteesRequestSchema: GenMessage<ListInviteesRequest>;

/**
 * @generated from message invite.ListInviteesResponse
 */
export declare type ListInviteesResponse = Message<"invite.ListInviteesResponse"> & {
  /**
   * @generated from field: repeated invite.InviteeWithStatus invitees = 1;
   */
  invitees: InviteeWithStatus[];
};

/**
 * Describes the message invite.ListInviteesResponse.
 * Use `create(ListInviteesResponseSchema)` to create a new message.
 */
export declare const ListInviteesResponseSchema: GenMessage<ListInviteesResponse>;

/**
 * @generated from message invite.SubmitRSVPRequest
 */
export declare type SubmitRSVPRequest = Message<"invite.SubmitRSVPRequest"> & {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId: string;

  /**
   * @generated from field: string household_id = 2;
   */
  householdId: string;

  /**
   * @generated from field: invite.RSVPStatus status = 3;
   */
  status: RSVPStatus;

  /**
   * @generated from field: string emergency_contact_name = 4;
   */
  emergencyContactName: string;

  /**
   * @generated from field: string emergency_contact_phone = 5;
   */
  emergencyContactPhone: string;

  /**
   * @generated from field: repeated string attendee_person_ids = 6;
   */
  attendeePersonIds: string[];
};

/**
 * Describes the message invite.SubmitRSVPRequest.
 * Use `create(SubmitRSVPRequestSchema)` to create a new message.
 */
export declare const SubmitRSVPRequestSchema: GenMessage<SubmitRSVPRequest>;

/**
 * @generated from message invite.SubmitRSVPResponse
 */
export declare type SubmitRSVPResponse = Message<"invite.SubmitRSVPResponse"> & {
  /**
   * @generated from field: invite.RSVP rsvp = 1;
   */
  rsvp?: RSVP;

  /**
   * non-empty only when household has no owner yet
   *
   * @generated from field: string claim_token = 2;
   */
  claimToken: string;
};

/**
 * Describes the message invite.SubmitRSVPResponse.
 * Use `create(SubmitRSVPResponseSchema)` to create a new message.
 */
export declare const SubmitRSVPResponseSchema: GenMessage<SubmitRSVPResponse>;

/**
 * @generated from message invite.ListHouseholdsRequest
 */
export declare type ListHouseholdsRequest = Message<"invite.ListHouseholdsRequest"> & {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId: string;
};

/**
 * Describes the message invite.ListHouseholdsRequest.
 * Use `create(ListHouseholdsRequestSchema)` to create a new message.
 */
export declare const ListHouseholdsRequestSchema: GenMessage<ListHouseholdsRequest>;

/**
 * @generated from message invite.ListHouseholdsResponse
 */
export declare type ListHouseholdsResponse = Message<"invite.ListHouseholdsResponse"> & {
  /**
   * @generated from field: repeated invite.HouseholdGroup households = 1;
   */
  households: HouseholdGroup[];
};

/**
 * Describes the message invite.ListHouseholdsResponse.
 * Use `create(ListHouseholdsResponseSchema)` to create a new message.
 */
export declare const ListHouseholdsResponseSchema: GenMessage<ListHouseholdsResponse>;

/**
 * @generated from message invite.GetPersonRequest
 */
export declare type GetPersonRequest = Message<"invite.GetPersonRequest"> & {
  /**
   * @generated from field: string person_id = 1;
   */
  personId: string;

  /**
   * for unauthenticated RSVP callers
   *
   * @generated from field: string event_token = 2;
   */
  eventToken: string;
};

/**
 * Describes the message invite.GetPersonRequest.
 * Use `create(GetPersonRequestSchema)` to create a new message.
 */
export declare const GetPersonRequestSchema: GenMessage<GetPersonRequest>;

/**
 * @generated from message invite.ListPersonsRequest
 */
export declare type ListPersonsRequest = Message<"invite.ListPersonsRequest"> & {
  /**
   * for unauthenticated RSVP callers
   *
   * @generated from field: string event_token = 1;
   */
  eventToken: string;
};

/**
 * Describes the message invite.ListPersonsRequest.
 * Use `create(ListPersonsRequestSchema)` to create a new message.
 */
export declare const ListPersonsRequestSchema: GenMessage<ListPersonsRequest>;

/**
 * @generated from message invite.ListPersonsResponse
 */
export declare type ListPersonsResponse = Message<"invite.ListPersonsResponse"> & {
  /**
   * @generated from field: repeated invite.Person persons = 1;
   */
  persons: Person[];
};

/**
 * Describes the message invite.ListPersonsResponse.
 * Use `create(ListPersonsResponseSchema)` to create a new message.
 */
export declare const ListPersonsResponseSchema: GenMessage<ListPersonsResponse>;

/**
 * @generated from message invite.CreatePersonRequest
 */
export declare type CreatePersonRequest = Message<"invite.CreatePersonRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: invite.PersonType type = 2;
   */
  type: PersonType;

  /**
   * @generated from field: string phone = 3;
   */
  phone: string;

  /**
   * @generated from field: string email = 4;
   */
  email: string;
};

/**
 * Describes the message invite.CreatePersonRequest.
 * Use `create(CreatePersonRequestSchema)` to create a new message.
 */
export declare const CreatePersonRequestSchema: GenMessage<CreatePersonRequest>;

/**
 * @generated from message invite.CreateHouseholdRequest
 */
export declare type CreateHouseholdRequest = Message<"invite.CreateHouseholdRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message invite.CreateHouseholdRequest.
 * Use `create(CreateHouseholdRequestSchema)` to create a new message.
 */
export declare const CreateHouseholdRequestSchema: GenMessage<CreateHouseholdRequest>;

/**
 * @generated from message invite.AddHouseholdMemberRequest
 */
export declare type AddHouseholdMemberRequest = Message<"invite.AddHouseholdMemberRequest"> & {
  /**
   * @generated from field: string household_id = 1;
   */
  householdId: string;

  /**
   * @generated from field: string person_id = 2;
   */
  personId: string;

  /**
   * @generated from field: invite.MemberRole role = 3;
   */
  role: MemberRole;
};

/**
 * Describes the message invite.AddHouseholdMemberRequest.
 * Use `create(AddHouseholdMemberRequestSchema)` to create a new message.
 */
export declare const AddHouseholdMemberRequestSchema: GenMessage<AddHouseholdMemberRequest>;

/**
 * @generated from message invite.ClaimHouseholdRequest
 */
export declare type ClaimHouseholdRequest = Message<"invite.ClaimHouseholdRequest"> & {
  /**
   * @generated from field: string claim_token = 1;
   */
  claimToken: string;
};

/**
 * Describes the message invite.ClaimHouseholdRequest.
 * Use `create(ClaimHouseholdRequestSchema)` to create a new message.
 */
export declare const ClaimHouseholdRequestSchema: GenMessage<ClaimHouseholdRequest>;

/**
 * @generated from message invite.ClaimHouseholdResponse
 */
export declare type ClaimHouseholdResponse = Message<"invite.ClaimHouseholdResponse"> & {
};

/**
 * Describes the message invite.ClaimHouseholdResponse.
 * Use `create(ClaimHouseholdResponseSchema)` to create a new message.
 */
export declare const ClaimHouseholdResponseSchema: GenMessage<ClaimHouseholdResponse>;

/**
 * @generated from enum invite.PersonType
 */
export enum PersonType {
  /**
   * @generated from enum value: PERSON_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PERSON_TYPE_CHILD = 1;
   */
  CHILD = 1,

  /**
   * @generated from enum value: PERSON_TYPE_ADULT = 2;
   */
  ADULT = 2,
}

/**
 * Describes the enum invite.PersonType.
 */
export declare const PersonTypeSchema: GenEnum<PersonType>;

/**
 * @generated from enum invite.MemberRole
 */
export enum MemberRole {
  /**
   * @generated from enum value: MEMBER_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MEMBER_ROLE_CHILD = 1;
   */
  CHILD = 1,

  /**
   * @generated from enum value: MEMBER_ROLE_GUARDIAN = 2;
   */
  GUARDIAN = 2,
}

/**
 * Describes the enum invite.MemberRole.
 */
export declare const MemberRoleSchema: GenEnum<MemberRole>;

/**
 * @generated from enum invite.RSVPStatus
 */
export enum RSVPStatus {
  /**
   * @generated from enum value: RSVP_STATUS_UNSPECIFIED = 0;
   */
  RSVP_STATUS_UNSPECIFIED = 0,

  /**
   * @generated from enum value: RSVP_STATUS_CONFIRMED = 1;
   */
  RSVP_STATUS_CONFIRMED = 1,

  /**
   * @generated from enum value: RSVP_STATUS_DECLINED = 2;
   */
  RSVP_STATUS_DECLINED = 2,
}

/**
 * Describes the enum invite.RSVPStatus.
 */
export declare const RSVPStatusSchema: GenEnum<RSVPStatus>;

/**
 * @generated from service invite.InviteService
 */
export declare const InviteService: GenService<{
  /**
   * Event management (host only)
   *
   * @generated from rpc invite.InviteService.CreateEvent
   */
  createEvent: {
    methodKind: "unary";
    input: typeof CreateEventRequestSchema;
    output: typeof EventSchema;
  },
  /**
   * @generated from rpc invite.InviteService.GetEvent
   */
  getEvent: {
    methodKind: "unary";
    input: typeof GetEventRequestSchema;
    output: typeof EventSchema;
  },
  /**
   * Guest list management (host only)
   *
   * @generated from rpc invite.InviteService.AddInvitee
   */
  addInvitee: {
    methodKind: "unary";
    input: typeof AddInviteeRequestSchema;
    output: typeof InviteeSchema;
  },
  /**
   * @generated from rpc invite.InviteService.AddHouseholdInvitees
   */
  addHouseholdInvitees: {
    methodKind: "unary";
    input: typeof AddHouseholdInviteesRequestSchema;
    output: typeof AddHouseholdInviteesResponseSchema;
  },
  /**
   * @generated from rpc invite.InviteService.RemoveInvitee
   */
  removeInvitee: {
    methodKind: "unary";
    input: typeof RemoveInviteeRequestSchema;
    output: typeof RemoveInviteeResponseSchema;
  },
  /**
   * @generated from rpc invite.InviteService.ListInvitees
   */
  listInvitees: {
    methodKind: "unary";
    input: typeof ListInviteesRequestSchema;
    output: typeof ListInviteesResponseSchema;
  },
  /**
   * RSVP flow
   *
   * @generated from rpc invite.InviteService.SubmitRSVP
   */
  submitRSVP: {
    methodKind: "unary";
    input: typeof SubmitRSVPRequestSchema;
    output: typeof SubmitRSVPResponseSchema;
  },
  /**
   * @generated from rpc invite.InviteService.ListHouseholds
   */
  listHouseholds: {
    methodKind: "unary";
    input: typeof ListHouseholdsRequestSchema;
    output: typeof ListHouseholdsResponseSchema;
  },
  /**
   * Person / household (partial auth — see handler)
   *
   * @generated from rpc invite.InviteService.GetPerson
   */
  getPerson: {
    methodKind: "unary";
    input: typeof GetPersonRequestSchema;
    output: typeof PersonSchema;
  },
  /**
   * @generated from rpc invite.InviteService.ListPersons
   */
  listPersons: {
    methodKind: "unary";
    input: typeof ListPersonsRequestSchema;
    output: typeof ListPersonsResponseSchema;
  },
  /**
   * @generated from rpc invite.InviteService.CreatePerson
   */
  createPerson: {
    methodKind: "unary";
    input: typeof CreatePersonRequestSchema;
    output: typeof PersonSchema;
  },
  /**
   * @generated from rpc invite.InviteService.CreateHousehold
   */
  createHousehold: {
    methodKind: "unary";
    input: typeof CreateHouseholdRequestSchema;
    output: typeof HouseholdSchema;
  },
  /**
   * @generated from rpc invite.InviteService.AddHouseholdMember
   */
  addHouseholdMember: {
    methodKind: "unary";
    input: typeof AddHouseholdMemberRequestSchema;
    output: typeof HouseholdMemberSchema;
  },
  /**
   * Claim (authenticated)
   *
   * @generated from rpc invite.InviteService.ClaimHousehold
   */
  claimHousehold: {
    methodKind: "unary";
    input: typeof ClaimHouseholdRequestSchema;
    output: typeof ClaimHouseholdResponseSchema;
  },
}>;

