import json
import sys
import os
from http.server import BaseHTTPRequestHandler
from google.protobuf import json_format

# Add generated proto path at runtime (committed to repo, generated by buf generate)
_gen_path = os.path.join(os.path.dirname(__file__), "..", "gen", "python", "sup")
if _gen_path not in sys.path:
    sys.path.insert(0, _gen_path)

import sup_pb2  # noqa: E402 — path inserted above

# Add lib/ to path for domain and adapters modules
_lib_path = os.path.join(os.path.dirname(__file__), "..", "lib")
if _lib_path not in sys.path:
    sys.path.insert(0, _lib_path)

from domain.greeting import greet_sup  # noqa: E402
from adapters.mock.greeting_store import MockGreetingStore  # noqa: E402

_store = MockGreetingStore()


class handler(BaseHTTPRequestHandler):
    """Vercel Python serverless handler for SupService.SaySup (Connect-RPC unary over JSON)."""

    def do_POST(self):
        content_length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(content_length)

        try:
            req = json_format.Parse(body, sup_pb2.SupRequest())
        except Exception:
            error = json.dumps({"code": "invalid_argument", "message": "Invalid request body"}).encode()
            self.send_response(400)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(error)))
            self.end_headers()
            self.wfile.write(error)
            return

        message = greet_sup(req.name, _store)
        resp = sup_pb2.SupResponse(message=message)
        result = json_format.MessageToJson(resp, preserving_proto_field_name=True).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(result)))
        self.end_headers()
        self.wfile.write(result)

    def do_GET(self):
        error = json.dumps({"code": "unimplemented", "message": "Method not allowed"}).encode()
        self.send_response(405)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(error)))
        self.end_headers()
        self.wfile.write(error)
