import json
import sys
import os
from http.server import BaseHTTPRequestHandler

# Add generated proto Python path at runtime (generated by buf generate at deploy time)
_gen_path = os.path.join(os.path.dirname(__file__), "gen", "python")
if _gen_path not in sys.path:
    sys.path.insert(0, _gen_path)


class handler(BaseHTTPRequestHandler):
    """Vercel Python serverless handler for SupService.SaySup (Connect-RPC unary over JSON)."""

    def do_POST(self):
        content_length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(content_length)

        try:
            data = json.loads(body)
            name = data.get("name", "")
        except Exception:
            error = json.dumps({"code": "invalid_argument", "message": "Invalid request body"}).encode()
            self.send_response(400)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(error)))
            self.end_headers()
            self.wfile.write(error)
            return

        result = json.dumps({"message": f"Sup, {name}!"}).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(result)))
        self.end_headers()
        self.wfile.write(result)

    def do_GET(self):
        error = json.dumps({"code": "unimplemented", "message": "Method not allowed"}).encode()
        self.send_response(405)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(error)))
        self.end_headers()
        self.wfile.write(error)
